spring:
  application:
    name: travel-shopping-backend

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:travel_shopping;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

server:
  port: 8080

logging:
  level:
    com.goorm.travelshopping: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
